
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class DetailPanel extends javax.swing.JPanel {
  InstructionPanel insp;
  
  String id;
  public void setScholar(String id)
  {
      this.id=id;
      ScholarNo.setText(id);
      setData();
  }
  public void setData()
  {
       try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection ("jdbc:mysql://localhost:3306/microsoftexam", "root", "");
            Statement stmt = (Statement)con.createStatement();
            String query =" select * from studentlogin where D like "+id;
            //String query="SELECT name  FROM studentlogin "+"WHERE id='"+"141112043"+"';";
//String query =" select name from studentlogin where id like "+this.id;
            ResultSet rs=stmt.executeQuery(query);
            
            //rs.first();
            if(rs.next())
            {
                //JOptionPane.showMessageDialog(this,rs.getString("name") );
                String username=rs.getString("C");
                String mailid=rs.getString("E");
                String cno=rs.getString("F");
                if(cno!=null)
                    contactNo.setText(cno);
                
                mailId.setText(mailid);
                name.setText(username);
                ExamPanel.myName.setText(username);
                ExamPanel.myScholar.setText(id);
            }
            
               
           
        }
        catch (SQLException ex)
        {
            Logger.getLogger(DetailPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(DetailPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         
      
      
  }
  
    /**
     * 
     * Creates new form DetailPanel
     */
    public DetailPanel(Dimension d, InstructionPanel insp) 
    {
        this.insp=insp;
        this.setLayout(null);
        this.setBounds(0,0 ,d.width,d.height);
        this.setBackground(Color.GREEN);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        ScholarNo = new javax.swing.JTextField();
        contactNo = new javax.swing.JTextField();
        mailId = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Ok = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 0, 0));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 50));
        setForeground(new java.awt.Color(102, 0, 0));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fill  Details");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        add(jLabel1);
        jLabel1.setBounds(530, 40, 360, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        add(jLabel2);
        jLabel2.setBounds(390, 210, 60, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Scholar No.");
        add(jLabel3);
        jLabel3.setBounds(390, 260, 140, 22);

        Male.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Male.setText("Male");
        add(Male);
        Male.setBounds(620, 310, 80, 23);

        Female.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        add(Female);
        Female.setBounds(790, 300, 91, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Gender");
        add(jLabel4);
        jLabel4.setBounds(390, 310, 80, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Contact No.");
        add(jLabel5);
        jLabel5.setBounds(390, 350, 120, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("MailId");
        add(jLabel6);
        jLabel6.setBounds(390, 400, 140, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Address");
        add(jLabel7);
        jLabel7.setBounds(390, 450, 90, 22);

        name.setEditable(false);
        name.setBackground(new java.awt.Color(0, 0, 0));
        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name);
        name.setBounds(600, 200, 310, 30);

        ScholarNo.setEditable(false);
        ScholarNo.setBackground(new java.awt.Color(0, 0, 0));
        ScholarNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ScholarNo.setForeground(new java.awt.Color(255, 255, 255));
        ScholarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScholarNoActionPerformed(evt);
            }
        });
        add(ScholarNo);
        ScholarNo.setBounds(680, 260, 112, 30);

        contactNo.setBackground(new java.awt.Color(0, 0, 0));
        contactNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contactNo.setForeground(new java.awt.Color(255, 255, 255));
        add(contactNo);
        contactNo.setBounds(670, 350, 130, 30);

        mailId.setBackground(new java.awt.Color(0, 0, 0));
        mailId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mailId.setForeground(new java.awt.Color(255, 255, 255));
        mailId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(mailId);
        mailId.setBounds(590, 400, 320, 30);

        Address.setBackground(new java.awt.Color(0, 0, 0));
        Address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Address);
        Address.setBounds(590, 450, 320, 28);

        Ok.setBackground(new java.awt.Color(0, 0, 0));
        Ok.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Ok.setText("NEXT");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        add(Ok);
        Ok.setBounds(550, 530, 110, 37);
    }// </editor-fold>//GEN-END:initComponents

    public void insertDataToRecord()
    {
        String sch,nam,gender,cno,mail,address;
        sch=ScholarNo.getText();
        nam=name.getText();
        gender=Male.isSelected()?"Male":"Female";
        cno=contactNo.getText();
        mail=mailId.getText();
        address=Address.getText();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection ("jdbc:mysql://localhost:3306/microsoftexam", "root", "");
            Statement stmt = (Statement)con.createStatement();
            String query="INSERT INTO record VALUES('"+sch+"','"+nam+"'   ,  '"+gender+ "','"+cno+"','"+mail+"','"+address+"'   );";
           // JOptionPane.showMessageDialog(this, query);
            stmt.executeUpdate(query);
            con.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(DetailPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(DetailPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        insertDataToRecord();
        this.setVisible(false);
        insp.setVisible(true);
    }//GEN-LAST:event_OkActionPerformed

    private void ScholarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScholarNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScholarNoActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Male;
    private javax.swing.JButton Ok;
    private javax.swing.JTextField ScholarNo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JTextField contactNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mailId;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
