
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class InstructionPanel extends javax.swing.JPanel {

      ExamPanel ex;
  
    /**
     * Creates new form InstructionPanel
     */
    public InstructionPanel(Dimension d,  ExamPanel ex) {
        
        this.ex=ex;
        this.setLayout(null);
        this.setBounds(0,0 ,d.width,d.height);
        this.setBackground(Color.BLUE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        StartTest = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 51));
        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Read the instructions carefully");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(51, 51, 51)));
        add(jLabel1);
        jLabel1.setBounds(330, 20, 640, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("1. This is an online test containing 15 mcq questions ");
        add(jLabel2);
        jLabel2.setBounds(280, 240, 640, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("2. Each questions contains 1 mark,and has negative marking of 0.5");
        add(jLabel3);
        jLabel3.setBounds(280, 280, 820, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("3. Time limit : 1hour ");
        add(jLabel4);
        jLabel4.setBounds(280, 320, 604, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("4. Do Not open the new tab during exam");
        add(jLabel5);
        jLabel5.setBounds(280, 360, 604, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("5.Finally Submitt and Complete.");
        add(jLabel6);
        jLabel6.setBounds(280, 410, 604, 29);

        StartTest.setBackground(new java.awt.Color(0, 0, 0));
        StartTest.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        StartTest.setForeground(new java.awt.Color(255, 255, 255));
        StartTest.setText("Start Test");
        StartTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTestActionPerformed(evt);
            }
        });
        add(StartTest);
        StartTest.setBounds(460, 480, 211, 53);
    }// </editor-fold>//GEN-END:initComponents

    private void StartTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTestActionPerformed
        // TODO add your handling code here:
       // ex.fetchImage();
        
           
        
        
        
        
        
       ex.setTime();
        
        ex.fetchImage();
        ex.fetchData();
        this.setVisible(false);
        ex.setVisible(true);
    }//GEN-LAST:event_StartTestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StartTest;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
