
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class LoginPanel extends javax.swing.JPanel {

    DetailPanel dp; 
    private final String PASSWORD="12345";
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() 
    {
       
        
     
    }
     public LoginPanel(Dimension d,DetailPanel dp)
     {
         
        this.dp=dp;
        this.setLayout(null);
        this.setBounds(0,0 ,d.width,d.height);
        this.setBackground(Color.RED);
        initComponents();
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        Password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ScholarNo = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 50, true));
        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Scholar No.");
        add(jLabel1);
        jLabel1.setBounds(470, 200, 104, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(480, 260, 87, 22);

        ScholarNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ScholarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScholarNoActionPerformed(evt);
            }
        });
        add(ScholarNo);
        ScholarNo.setBounds(660, 200, 91, 30);

        Login.setBackground(new java.awt.Color(102, 102, 102));
        Login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(0, 0, 153));
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        add(Login);
        Login.setBounds(580, 330, 90, 50);

        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(password);
        password.setBounds(660, 260, 91, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Microsoft Online Examination");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel3);
        jLabel3.setBounds(330, 50, 735, 80);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        String s=ScholarNo.getText().toString();
         if(validatePass()&&validateScholar(s))
         {
            dp.setScholar(s);
            this.setVisible(false);
            dp.setVisible(true);
         }
         else
             JOptionPane.showMessageDialog(LoginPanel.this,"Fill correct details");
        
        
    }//GEN-LAST:event_LoginActionPerformed

    private void ScholarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScholarNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScholarNoActionPerformed
    private boolean validateScholar(String id )
       {
        
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection ("jdbc:mysql://localhost:3306/microsoftexam", "root", "");
            Statement stmt = (Statement)con.createStatement();
            String query =" select * from studentlogin where D like "+id;
            ResultSet rs=stmt.executeQuery(query);
            if(rs.next())
            {
                return true;
            }
             con.close();
        }
        catch (SQLException ex)
        {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           return false;
       }
    private boolean validatePass()
    {
        if(password.getText().trim().equals(PASSWORD))
        {
            return true;
        }
        return false;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField ScholarNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
